### ISSUE TITLE
Compile code in any language without installing compiler

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#143]
## Feature description:
The user should be able to compile their code written in any programming language without installing a compiler for the language.

## Any ideas on how to implement it?
- Online API's like that provided by HackerEarth can be used.
- example implementation: [ComIt](https://github.com/imshyam/ComIt)

**Comment by cyberlis** [comment]
I would like to take this issue.

**Comment by manparvesh** [comment]
@cyberlis 
Sure! I'd be glad to review your PR!

**Comment by cyberlis** [comment]
> @cyberlis
> Sure! I'd be glad to review your PR!

Sorry, I don't have enough time to make this feature. Maybe, somebody else can take it.

**Comment by csaranbalaji** [comment]
I would like to take this issue. 

I tried to run the code through hackerearth client which is given [here](https://www.hackerearth.com/docs/wiki/developers/v3/). Unfortunately the response was 
`{
  u'run_status': {
    u'status': u'CE',
    u'status_detail': u'Correct the compilation/syntax errors.'
  },
  u'code_id': u'3f9b8et',
  u'web_link': u'https://code.hackerearth.com/3f9b8et',
  u'compile_status': u'Error code: 1200'
}`

but when I checked the link which is available in the json('web_link'), the code runs fine there. 

Probably, that should be an issue with hackerearth API because their [official client](https://github.com/HackerEarth/he-sdk-python/blob/master/hackerearth/test_api.py) also throws the same error code.

**Comment by csaranbalaji** [comment]
The hackerearth API issue is fixed now. I'll proceed with it.

**Comment by manparvesh** [comment]
Continuing this issue in #210
