### ISSUE TITLE
View previous day or week's notes

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#41]
Feature description:
-------------------
Add functionality to view notes from previous days by simply writing `yoda diary notes yesterday` or something similar

**Comment by saurabh-kumar-vit** [comment]
I would like to take up this task.

**Comment by saurabh-kumar-vit** [comment]
To complete this task I think I might have to add a new command to ```check_sub_command``` in ```diary.py```. 

But all the other commands are only one world, while this includes the term for the history as well, so it might be more reasonable to parse it in the ```notes``` functions. But I am unable to understand how I would be able to get the history term in the ```notes``` function.

As in the ```process``` function we are only doing a ```strip()``` so this must be under the assumption that there is only one word/command to parse. Would we need to change ```process``` as well to add this new feature.

**Comment by manparvesh** [comment]
@saurabh-kumar-vit :+1: sure

**Comment by saurabh-kumar-vit** [comment]
@manparvesh I am unable to understand where to parse the new argument for notes history.

should it be done in
1. yoda module where collect the command line arguments
2. Or in the diary module. should we make ```notes``` a separate function like the url shorten function.

to me the second option looks the easiest since it can be implemented without breaking any of the existing diary code. But I was hoping to get a better suggestion from you.

**Comment by stepinski** [comment]
May I take this task?

**Comment by manparvesh** [comment]
@stepinski sure!

**Comment by karuvally** [comment]
I have created a pull request which adds the ability to see yesterday's notes and tasks
